export async function adminListAllJobs() {
  return [
    {
      id: "j100",
      title: "Staff Nurse",
      company: "Global Enterprises",
      stream: "Healthcare",
      category: "Nurses",
      subCategory: "Staff Nurse",
      location: "Hyderabad",
      salary: "₹25k–40k",
      experience: "0-2 yrs",
      status: "active",
      createdAt: "2026-02-15",
      applications: 210,
    },
    {
      id: "j101",
      title: "Senior Developer",
      company: "Tech Solutions Inc.",
      stream: "IT",
      category: "Software",
      subCategory: "Full Stack",
      location: "Bangalore",
      salary: "₹10–15 LPA",
      experience: "3-5 yrs",
      status: "active",
      createdAt: "2026-02-14",
      applications: 120,
    },
    {
      id: "j102",
      title: "Mechanical Engineer",
      company: "Innovation Corp",
      stream: "Engineering",
      category: "Mechanical",
      subCategory: "Production",
      location: "Chennai",
      salary: "₹6–9 LPA",
      experience: "2-4 yrs",
      status: "disabled",
      createdAt: "2026-02-13",
      applications: 60,
    },
    {
      id: "j103",
      title: "UI/UX Designer",
      company: "Tech Solutions Inc.",
      stream: "Design",
      category: "UI/UX",
      subCategory: "Product Design",
      location: "Remote",
      salary: "₹6–10 LPA",
      experience: "1-3 yrs",
      status: "active",
      createdAt: "2026-02-12",
      applications: 80,
    },
  ];
}
